"""hieght

Revision ID: 2d513b7fef7f
Revises: 8dcaccf3ef96
Create Date: 2024-07-12 11:40:27.554373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d513b7fef7f'
down_revision: Union[str, None] = '8dcaccf3ef96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'height')
    # ### end Alembic commands ###
